config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :learnables
  resources :shareables
  resources :skills do
    get :autocomplete_skill_name, :on => :collection
  end

  root to: 'home#index'

end

app/models/learnable.rb
class Learnable < ActiveRecord::Base
  belongs_to :user
  has_one :skill
end

app/models/matchup.rb
class Matchup < ActiveRecord::Base
end

app/models/shareable.rb
class Shareable < ActiveRecord::Base
  belongs_to :user
  has_one :skill
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  has_many :learnables
  has_many :shareables
  has_one :profile

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(username: data["name"],
           email: data["email"],
           password: Devise.friendly_token[0,20]
        )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def find_matching_shareables skill_id
    Shareable.where(skill_id: skill_id)
  end

  def find_matching_learnables skill_id
    Learnable.where(skill_id: skill_id)
  end

  def find_matchups skill_id
    Matchup.where(skill_id: skill_id)
  end

  helper_method :find_matching_shareables
  helper_method :find_matching_learnables
  helper_method :find_matchups

end

app/controllers/learnables_controller.rb
class LearnablesController < ApplicationController

  autocomplete :skill, :full => true, :limit => 10

  def new
    @learnable = Learnable.new
  end

  def create
    skill = Skill.where(name: params['learnable']['skill']).first_or_create
    Learnable.create(user_id: current_user.id, skill_id: skill.id)
    check_for_matches_and_build_matchup skill.id
    redirect_to '/'
  end

  def check_for_matches_and_build_matchup skill_id
    return nil if Matchup.exists?(skill_id: skill_id, learner_id: current_user.id)
    shareable_found = Shareable.where(skill_id: skill_id).first
    if shareable_found
      Matchup.create(skill_id: skill_id, sharer_id: shareable_found.user_id, learner_id: current_user.id)
    end
  end

end

app/controllers/shareables_controller.rb
class ShareablesController < ApplicationController

  autocomplete :skill, :full => true, :limit => 10

  def new
    @shareable = Shareable.new
  end

  def create
    skill = Skill.where(name: params['shareable']['skill']).first_or_create
    Shareable.create(user_id: current_user.id, skill_id: skill.id)
    check_for_matches_and_build_matchup skill.id
    redirect_to '/'
  end

  def check_for_matches_and_build_matchup skill_id
    return nil if Matchup.exists?(skill_id: skill_id, sharer_id: current_user.id)
    learnable_found = Learnable.where(skill_id: skill_id).first
    if learnable_found
      Matchup.create(skill_id: skill_id, sharer_id: current_user.id, learner_id: learnable_found.user_id)
    end
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  autocomplete :skill, :name, :full => true, :limit => 10

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/learnables_helper.rb
module LearnablesHelper
end

app/helpers/shareables_helper.rb
module ShareablesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/home/index.html.erb
<div class="Center site">
  <h1>SkillExchange</h1>
</div>

<script src='instanthangouts.0.1.0.js' async></script>

<section id="links-holder">
  <span class="link-to-skill" id="link-learn">
    <%= link_to 'Learn something', new_learnable_path %>
  </span>
  <span class="link-to-skill" id="link-teach">
    <%= link_to 'Teach something', new_shareable_path %>
  </span>
</section>

<% if user_signed_in? %>

  <% if current_user.learnables.any? %>
    <section class="skill-section" id="learnables">
      <p class="sub-title">My learnables</p>
      <ul class="skill-list" id="learnable-list">
        <% current_user.learnables.each do |learnable| %>
          <li class="skill-item" id="learnable-item">
            <p class="skill-name"><%= Skill.find(learnable.skill_id).name %></p>
              <% if find_matchups(learnable.skill_id).length > 0 %>
                <% find_matchups(learnable.skill_id).each do |matchup| %>
                  <span class="match"><%= "#{User.find(matchup.sharer_id).username} knows #{Skill.find(matchup.skill_id).name}" %><div class='instanthangouts' render='hangout' publisher_id:"123" room_id=<%= matchup.id %> topic=<%= "#{Skill.find(matchup.skill_id).name}" %>><%= instant_hangout %></div>
                  </span>
              <% end %>
            <% end %>
          </li>
        </ul>
      <% end %>
    </section>
  <% end %>
    
  <% if current_user.shareables.any? %>
    <section class="skill-section" id="shareables">
      <p class="sub-title">My shareables</p>
      <ul class="skill-list" id="shareable-list">
        <% current_user.shareables.each do |shareable| %>
          <li class="skill-item" id="shareable-item">
            <p class="skill-name"><%= Skill.find(shareable.skill_id).name %></p>
              <% if find_matchups(shareable.skill_id).length > 0 %>
                <% find_matchups(shareable.skill_id).each do |matchup| %>
                  <span class="match"><%= "#{User.find(matchup.learner_id).username} wants to learn #{Skill.find(matchup.skill_id).name}" %><div class='instanthangouts' render='hangout' publisher_id:"123" room_id=<%= matchup.id %> topic=<%= "#{Skill.find(matchup.skill_id).name}" %>><%= instant_hangout %></div>
                  </span>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </section>
  <% end %>

<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    SkillExchange
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'about_path' %></li>
      <li><%= link_to "Contact", 'contact_path' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse"> 
  <div class="container">
    <%= link_to "SkillExchange", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>SkillExchange</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'jquery-ui.min.js', 'autocomplete-rails.js', 'rails.js'  %>
    <%= stylesheet_link_tag 'jquery-ui.css' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <!--
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path,  method: :delete, class: "btn btn-lg btn-default" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-lg btn-primary" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-lg btn-primary" %>
        <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), class: "btn btn-lg btn-primary" %>
    <% end %>
      -->
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/learnables/new.html.erb
<%= form_for @learnable do |f| %>
  <%= f.label :skill %>
  <%= f.autocomplete_field :skill, autocomplete_skill_name_skills_path %>
  <%= f.submit 'Add learnable' %>
<% end %>

app/views/shareables/new.html.erb
<%= form_for @shareable do |f| %>
  <%= f.label :skill %>
  <%= f.autocomplete_field :skill, autocomplete_skill_name_skills_path %>
  <%= f.submit 'Add shareable' %>
<% end %>